apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.name }}-serving-cert
spec:
  dnsNames:
  - {{ .Values.name }}-webhook-service.{{ .Release.Namespace }}.svc
  - {{ .Values.name }}-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: {{ .Values.name }}-selfsigned-issuer
  secretName: {{ .Values.name }}-webhook-service-cert
