---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.name }}-manager-rolebinding
  labels:
  {{- include "logstash-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: logstash-operator-manager-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.name }}-controller-manager
    namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.name }}-proxy-rolebinding
  labels:
  {{- include "logstash-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.name }}-proxy-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Release.Namespace }}
