apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
  {{- include "logstash-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicasCount }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
  {{- include "logstash-operator.selector.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "logstash-operator.selector.labels" . | nindent 8 }}
      {{- with .Values.annotations }}
      annotations:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.name }}-controller-manager
      securityContext:
      {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.operator.proxy.name }}
          ports:
          - containerPort: {{ .Values.operator.service.targetPort }}
            name: {{ .Values.operator.service.name }}
            protocol: TCP
          args:
          - --secure-listen-address=0.0.0.0:{{ .Values.operator.service.targetPort }}
          - --upstream=http://127.0.0.1:8080/
          - --logtostderr=true
          - --v=10
          image: {{ .Values.operator.proxy.image }}
          imagePullPolicy: {{ .Values.operator.proxy.imagePullPolicy }}
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
        - name: {{ .Values.operator.manager.name }}
          securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.operator.manager.image }}
          imagePullPolicy: {{ .Values.operator.proxy.imagePullPolicy }}
          args:
          - --health-probe-bind-address=:{{ .Values.livenessProbe.httpGet.port }}
          - --metrics-bind-address=127.0.0.1:8080
          - --leader-elect
          command:
            - /manager
          ports:
            - name: {{ .Values.webhook.service.name }}
              containerPort: {{ .Values.webhook.service.targetPort }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with $.Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
