---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-metrics-service
  labels:
  {{- include "logstash-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.operator.service.port }}
      targetPort: {{ .Values.operator.service.targetPort }}
      protocol: TCP
      name: {{ .Values.operator.service.name }}
  selector:
  {{- include "logstash-operator.selector.labels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-webhook-service
  labels:
  {{- include "logstash-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.webhook.service.port }}
      targetPort: {{ .Values.webhook.service.targetPort }}
      protocol: TCP
      name: {{ .Values.webhook.service.name }}
  selector:
  {{- include "logstash-operator.selector.labels" . | nindent 4 }}
